name: mplhep_env
channels:
  - conda-forge
dependencies:
  - python ==3.8
  - pip
  - pandas
  - matplotlib
  - boost-histogram >=0.10.0
  - jupyterlab >=2
  - rise
  - jupyter_contrib_nbextensions
  - jupyter_nbextensions_configurator
  - mscorefonts
  - pip:
    - hist >=2.0.0a5
    - mplhep >=0.1.27
    - uproot4
    - scikit-hep-testdata
